In [1]:
import tensorflow as tf
import numpy as np

In [16]:
from numpy import genfromtxt
my_data = genfromtxt('train.csv - train.csv.csv', delimiter=',')

In [17]:
y_prices=my_data[:,9]

In [18]:
x_data=my_data[:, :8]

In [19]:
x_data[0]

array([  8.45000000e+03,   8.56000000e+02,   8.54000000e+02,
         2.00000000e+00,   1.00000000e+00,   3.00000000e+00,
         1.00000000e+00,   8.00000000e+00])

In [20]:
x = tf.placeholder(tf.float64, [None, 8])
W = tf.Variable(tf.zeros([1, 8], dtype=tf.float64))
b = tf.Variable(tf.zeros([1], dtype=tf.float64))

In [21]:
sess = tf.InteractiveSession()

In [22]:
y = tf.matmul(x, tf.transpose(W)) + b

In [23]:
y_ = tf.placeholder(tf.float64, (None, 1))

In [34]:
#cost = tf.reduce_sum(tf.sqrt(tf.pow(y_-y, 2)))
#cost = tf.reduce_sum(tf.sqrt(tf.pow((y-y_), 2)))/1459
cost = tf.reduce_sum(tf.squared_difference(y_, y))
train = tf.train.GradientDescentOptimizer(0.0001).minimize(cost)

In [35]:
init = tf.global_variables_initializer()

In [36]:
sess.run(init)

In [37]:
print(sess.run(W))

[[ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [38]:
sess.run(b)

array([ 0.])

In [39]:
log = []
for j in range(101):
    if j%10 == 0:
        print("on " + str(j))
    for i in range(len(x_data)):
        xs = x_data[i].reshape(1,8)
        ys = y_prices[i].reshape(1,1)
        sess.run(train, feed_dict={x: xs, 
                                   y_: ys})

on 0
on 10
on 20
on 30
on 40
on 50
on 60
on 70
on 80
on 90
on 100


In [40]:
j=1
print(sess.run(y, feed_dict={x:x_data[j].reshape((1,8)), y_:y_prices[j].reshape((1,1))}))

[[ nan]]


In [31]:
x_data[2]

array([  1.12500000e+04,   9.20000000e+02,   8.66000000e+02,
         2.00000000e+00,   1.00000000e+00,   3.00000000e+00,
         1.00000000e+00,   6.00000000e+00])

In [ ]:
print(sess.run(cost, feed_dict={x:x_data.reshape((len(x_data), 8)), y_:y_prices.reshape((len(y_prices), 1))}))

In [ ]:
plt.plot(input_x, output_y, 'ro', label='Origianl data')
